#encoding=utf-8 

# composite.py
# Python implementation of Composite design-model
# Generated by Elvis
# Created on: 1-may-2016

class Company: 

    name = '' 

    def __init__(self, name): 
        self.name = name 
         
    def Add(self, company): 
        pass      

    def Remove(self, company): 
        pass  

    def Display(self, depth): 
        pass  

    def LineOfDuty(self): 
        pass  

class ConcreteCompany(Company): 

    childrenCompany = None     

    def __init__(self, name): 
        Company.__init__(self,name) 
        self.childrenCompany = [] 

    def Add(self, company): 
        self.childrenCompany.append(company)  
    
    def Remove(self, company): 
        self.childrenCompany.remove(company)  

    def Display(self, depth): 
        printInfo('-'*depth + self.name) 
        for component in self.childrenCompany: 
            component.Display(depth+2) 

    def LineOfDuty(self): 
        for component in self.childrenCompany: 
            component.LineOfDuty()     

class HRDepartment(Company):    
    def __init__(self, name): 
         Company.__init__(self,name) 

    def Display(self, depth): 
        printInfo('-'*depth + self.name) 
        
    def LineOdDuty(self):
        printInfo('%s\t stuff managerment' % self.name) 

  

class FinanceDepartment(Company):     
    def __init__(self, name): 
        Company.__init__(self,name) 

    def Display(self, depth): 
        printInfo('-'*depth + self.name) 

    def LineOfDuty(self): 
        printInfo('%s\t the finanace of company' % self.name) 

 

def clientUI():     
    root = ConcreteCompany('beijing company') 
    root.Add(HRDepartment('bj HR department')) 
    root.Add(FinanceDepartment('bj finance department') 
     
    comp = ConcreteCompany('north of china')
    comp.Add(HRDepartment('north of china HR')) 
    comp.Add(FinanceDepartment('north of china finance')) 
    root.Add(comp) 

    comp1 = ConcreteCompany('nan jing place') 
    comp1.Add(HRDepartment('nj HR department')) 
    comp1.Add(FinanceDepartment('nj finance department')) 
    comp.Add(comp1) 

    comp2 = ConcreteCompany('hangzhou place') 
    comp2.Add(HRDepartment('hz HR deparment')) 
    comp2.Add(FinanceDepartment('hz finance department')) 
    comp.Add(comp2)     

     

    printInfo('-------strucment of company-------') 

    root.Display(1) 

     

    printInfo('\n-------ְduty-------') 

    root.LineOfDuty() 

    return 

 

if __name__ == '__main__': 

    clientUI();